include:
  - common.yml

services:
  ollama:
    image: ollama/ollama:rocm
    ports:
      - "11434:11434"
    volumes:
      - ollama_amd_data:/root/.ollama
    restart: always
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    # Optional environment variable for specific AMD architectures
    # environment:
    #   - HSA_OVERRIDE_GFX_VERSION=10.3.0
    networks:
      - kuab-network

volumes:
  ollama_amd_data:
